[package]
name = "bkupman"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0.86"
getopts = "0.2.21"
log = "0.4.21"
serde = "1.0.203"
serde_json = "1.0.117"

[dev-dependencies]
tempdir = "0.3.7"
